version: '3'

services:
  web:
    build: .
    command: bash -c "gunicorn lynkly.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A lynkly worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A lynkly beat -l info
    volumes:
      - .:/app
    depends_on:
      - celery
      - redis

  redis:
    image: "redis:alpine"

