version: '3.9'

services:
  celery:
    build: .
    command: ["./wait-for-it.sh", "redis:6379", "--", "celery", "-A", "lynkly", "worker", "--pool=solo", "-l", "INFO"]
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: ["./wait-for-it.sh", "redis:6379", "--", "celery", "-A", "lynkly", "beat", "-l", "INFO"]
    volumes:
      - .:/app
    depends_on:
      - celery
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
